<?php
$data = array (
  649 => 
  array (
    'cat_id' => '649',
    'cat_name' => '工艺',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '649',
    'name' => '工艺',
  ),
  590 => 
  array (
    'cat_id' => '590',
    'cat_name' => '错金',
    'measure_unit' => '',
    'parent_id' => '649',
    'is_show' => '0',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 791,
    'level' => 1,
    'id' => '590',
    'name' => '错金',
  ),
  423 => 
  array (
    'cat_id' => '423',
    'cat_name' => '金镶玉',
    'measure_unit' => '',
    'parent_id' => '649',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '0',
    'goods_num' => 19,
    'level' => 1,
    'id' => '423',
    'name' => '金镶玉',
  ),
  650 => 
  array (
    'cat_id' => '650',
    'cat_name' => '雕刻',
    'measure_unit' => '',
    'parent_id' => '649',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 2,
    'level' => 1,
    'id' => '650',
    'name' => '雕刻',
  ),
  651 => 
  array (
    'cat_id' => '651',
    'cat_name' => '嵌宝',
    'measure_unit' => '',
    'parent_id' => '649',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '651',
    'name' => '嵌宝',
  ),
  631 => 
  array (
    'cat_id' => '631',
    'cat_name' => '器形',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '631',
    'name' => '器形',
  ),
  635 => 
  array (
    'cat_id' => '635',
    'cat_name' => '手把件',
    'measure_unit' => '',
    'parent_id' => '631',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '635',
    'name' => '手把件',
  ),
  632 => 
  array (
    'cat_id' => '632',
    'cat_name' => '手镯',
    'measure_unit' => '',
    'parent_id' => '631',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '632',
    'name' => '手镯',
  ),
  654 => 
  array (
    'cat_id' => '654',
    'cat_name' => '手串',
    'measure_unit' => '',
    'parent_id' => '631',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '654',
    'name' => '手串',
  ),
  636 => 
  array (
    'cat_id' => '636',
    'cat_name' => '摆件',
    'measure_unit' => '',
    'parent_id' => '631',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '636',
    'name' => '摆件',
  ),
  633 => 
  array (
    'cat_id' => '633',
    'cat_name' => '挂件',
    'measure_unit' => '',
    'parent_id' => '631',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '633',
    'name' => '挂件',
  ),
  637 => 
  array (
    'cat_id' => '637',
    'cat_name' => '戒指',
    'measure_unit' => '',
    'parent_id' => '631',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '637',
    'name' => '戒指',
  ),
  634 => 
  array (
    'cat_id' => '634',
    'cat_name' => '吊坠',
    'measure_unit' => '',
    'parent_id' => '631',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '634',
    'name' => '吊坠',
  ),
  638 => 
  array (
    'cat_id' => '638',
    'cat_name' => '材料',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '12',
    'goods_num' => 0,
    'level' => 0,
    'id' => '638',
    'name' => '材料',
  ),
  648 => 
  array (
    'cat_id' => '648',
    'cat_name' => '玛瑙',
    'measure_unit' => '',
    'parent_id' => '638',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '648',
    'name' => '玛瑙',
  ),
  645 => 
  array (
    'cat_id' => '645',
    'cat_name' => '翡翠',
    'measure_unit' => '',
    'parent_id' => '638',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '645',
    'name' => '翡翠',
  ),
  642 => 
  array (
    'cat_id' => '642',
    'cat_name' => '黄玉',
    'measure_unit' => '',
    'parent_id' => '638',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '642',
    'name' => '黄玉',
  ),
  639 => 
  array (
    'cat_id' => '639',
    'cat_name' => '白玉',
    'measure_unit' => '',
    'parent_id' => '638',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '639',
    'name' => '白玉',
  ),
  646 => 
  array (
    'cat_id' => '646',
    'cat_name' => '籽料',
    'measure_unit' => '',
    'parent_id' => '638',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '646',
    'name' => '籽料',
  ),
  643 => 
  array (
    'cat_id' => '643',
    'cat_name' => '墨玉',
    'measure_unit' => '',
    'parent_id' => '638',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '643',
    'name' => '墨玉',
  ),
  640 => 
  array (
    'cat_id' => '640',
    'cat_name' => '碧玉',
    'measure_unit' => '',
    'parent_id' => '638',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '640',
    'name' => '碧玉',
  ),
  630 => 
  array (
    'cat_id' => '630',
    'cat_name' => '独山玉',
    'measure_unit' => '',
    'parent_id' => '638',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '630',
    'name' => '独山玉',
  ),
  647 => 
  array (
    'cat_id' => '647',
    'cat_name' => '原石',
    'measure_unit' => '',
    'parent_id' => '638',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '647',
    'name' => '原石',
  ),
  644 => 
  array (
    'cat_id' => '644',
    'cat_name' => '青花',
    'measure_unit' => '',
    'parent_id' => '638',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '644',
    'name' => '青花',
  ),
  641 => 
  array (
    'cat_id' => '641',
    'cat_name' => '青玉',
    'measure_unit' => '',
    'parent_id' => '638',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '641',
    'name' => '青玉',
  ),
  653 => 
  array (
    'cat_id' => '653',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '638',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 3,
    'level' => 1,
    'id' => '653',
    'name' => '其他',
  ),
);
?>