<?php
$data = array (
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '玉石知识',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => '',
    'file_img' => '',
    'update_time' => '0',
    'has_children' => '0',
    'aricle_num' => '1630',
    'level' => 0,
    'id' => '20',
    'name' => '玉石知识',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '系统分类',
    'cat_type' => '2',
    'keywords' => '',
    'cat_desc' => '系统保留分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => '',
    'file_img' => '',
    'update_time' => '0',
    'has_children' => '4',
    'aricle_num' => '0',
    'level' => 0,
    'id' => '1',
    'name' => '系统分类',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '淘玉公告',
    'cat_type' => '3',
    'keywords' => '淘玉商城公告,淘玉商城新闻,淘玉资讯,淘玉玉石新闻',
    'cat_desc' => '淘玉公告专门为淘玉大事，淘玉公布新活动，新成果和想和大家分享的文章帮助文档等。',
    'sort_order' => '1',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'path_name' => 'gonggao',
    'file_img' => '',
    'update_time' => '0',
    'has_children' => '0',
    'aricle_num' => '110',
    'level' => 1,
    'id' => '30',
    'name' => '淘玉公告',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '网店信息',
    'cat_type' => '3',
    'keywords' => '',
    'cat_desc' => '网店信息分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'path_name' => '',
    'file_img' => '',
    'update_time' => '0',
    'has_children' => '0',
    'aricle_num' => '0',
    'level' => 1,
    'id' => '2',
    'name' => '网店信息',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '网店帮助分类',
    'cat_type' => '4',
    'keywords' => '',
    'cat_desc' => '网店帮助分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'path_name' => '',
    'file_img' => '',
    'update_time' => '0',
    'has_children' => '4',
    'aricle_num' => '0',
    'level' => 1,
    'id' => '3',
    'name' => '网店帮助分类',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '关于我们 ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '联系我们 ',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'path_name' => '',
    'file_img' => '',
    'update_time' => '0',
    'has_children' => '0',
    'aricle_num' => '7',
    'level' => 2,
    'id' => '9',
    'name' => '关于我们 ',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '配送方式 ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '配送与支付 ',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'path_name' => '',
    'file_img' => '',
    'update_time' => '0',
    'has_children' => '0',
    'aricle_num' => '5',
    'level' => 2,
    'id' => '7',
    'name' => '配送方式 ',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '售后服务',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'path_name' => '',
    'file_img' => '',
    'update_time' => '0',
    'has_children' => '0',
    'aricle_num' => '7',
    'level' => 2,
    'id' => '8',
    'name' => '售后服务',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '新手上路 ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'path_name' => '',
    'file_img' => '',
    'update_time' => '0',
    'has_children' => '0',
    'aricle_num' => '13',
    'level' => 2,
    'id' => '5',
    'name' => '新手上路 ',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => 'app帮助文档',
    'cat_type' => '4',
    'keywords' => '淘玉app帮助文档,淘玉app,淘玉app怎么用,淘玉app使用说明',
    'cat_desc' => '淘玉app帮助文档专业为玉友们设计操作的淘玉app帮助说明文档。涵盖app所有小功能和一些操作技巧，让玉友更方便的来选购自己的玉石产品',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'path_name' => 'apphelp',
    'file_img' => '',
    'update_time' => '0',
    'has_children' => '0',
    'aricle_num' => '13',
    'level' => 1,
    'id' => '32',
    'name' => 'app帮助文档',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '热点透视',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => 'rd',
    'file_img' => '',
    'update_time' => '0',
    'has_children' => '0',
    'aricle_num' => '35',
    'level' => 0,
    'id' => '25',
    'name' => '热点透视',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '鉴定知识',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => '',
    'file_img' => '',
    'update_time' => '0',
    'has_children' => '0',
    'aricle_num' => '1082',
    'level' => 0,
    'id' => '17',
    'name' => '鉴定知识',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '玉史长河',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => '',
    'file_img' => '',
    'update_time' => '0',
    'has_children' => '0',
    'aricle_num' => '146',
    'level' => 0,
    'id' => '21',
    'name' => '玉史长河',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '和田玉',
    'cat_type' => '1',
    'keywords' => '和田玉资讯,和田玉鉴定,和田玉,和田玉哪家好,和田玉官方,和田玉官网',
    'cat_desc' => '淘玉和田玉资讯平台，有和田白玉，和田碧玉，和田青花，和田籽料等不同和田玉保养小知识、价格、鉴别、估价等专业和田玉交流购物平台',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => 'hetian',
    'file_img' => '',
    'update_time' => '0',
    'has_children' => '0',
    'aricle_num' => '31',
    'level' => 0,
    'id' => '29',
    'name' => '和田玉',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '名家荟萃',
    'cat_type' => '1',
    'keywords' => '名家荟萃,玉石名家,玉石大师,玉石爱好者,玉友,翡翠名家,和田玉名家',
    'cat_desc' => '淘玉商城玉石名家荟萃频道，专业玉石名家畅谈玉石之美、玉石之魂、玉石之意，名家荟萃栏目是玉石爱好者的集聚地有翡翠名家、和田玉名家、鉴宝名家和各大玉石收藏家。',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => 'mingjia',
    'file_img' => '',
    'update_time' => '0',
    'has_children' => '0',
    'aricle_num' => '76',
    'level' => 0,
    'id' => '22',
    'name' => '名家荟萃',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '业界新闻',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => '',
    'file_img' => '',
    'update_time' => '0',
    'has_children' => '0',
    'aricle_num' => '2894',
    'level' => 0,
    'id' => '14',
    'name' => '业界新闻',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '选购技巧',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => '',
    'file_img' => '',
    'update_time' => '0',
    'has_children' => '0',
    'aricle_num' => '476',
    'level' => 0,
    'id' => '26',
    'name' => '选购技巧',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '玉石历史',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => '',
    'file_img' => '',
    'update_time' => '0',
    'has_children' => '0',
    'aricle_num' => '89',
    'level' => 0,
    'id' => '18',
    'name' => '玉石历史',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '拍卖展会',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => '',
    'file_img' => '',
    'update_time' => '0',
    'has_children' => '0',
    'aricle_num' => '18',
    'level' => 0,
    'id' => '23',
    'name' => '拍卖展会',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '玉石分类',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => '',
    'file_img' => '',
    'update_time' => '0',
    'has_children' => '0',
    'aricle_num' => '109',
    'level' => 0,
    'id' => '15',
    'name' => '玉石分类',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '收藏知识',
    'cat_type' => '1',
    'keywords' => '资讯,翡翠价格,翡翠鉴定,翡翠知识,翡翠新闻',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => '',
    'file_img' => '',
    'update_time' => '0',
    'has_children' => '0',
    'aricle_num' => '326',
    'level' => 0,
    'id' => '27',
    'name' => '收藏知识',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '玉石行情',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => '',
    'file_img' => '',
    'update_time' => '0',
    'has_children' => '0',
    'aricle_num' => '615',
    'level' => 0,
    'id' => '19',
    'name' => '玉石行情',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '投资收藏',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => '',
    'file_img' => '',
    'update_time' => '0',
    'has_children' => '0',
    'aricle_num' => '269',
    'level' => 0,
    'id' => '24',
    'name' => '投资收藏',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '玉石保养',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => '',
    'file_img' => '',
    'update_time' => '0',
    'has_children' => '0',
    'aricle_num' => '273',
    'level' => 0,
    'id' => '16',
    'name' => '玉石保养',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '翡翠资讯',
    'cat_type' => '1',
    'keywords' => '翡翠资讯,翡翠价格,翡翠鉴定,翡翠知识,翡翠新闻',
    'cat_desc' => '淘玉翡翠资讯平台，专业为翡翠爱好者提供翡翠交流资讯频道。提供翡翠鉴别，翡翠保养小知识，翡翠价格，翡翠估价，翡翠种类区分等专业翡翠交流购物平台',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'path_name' => 'feicui',
    'file_img' => '',
    'update_time' => '0',
    'has_children' => '0',
    'aricle_num' => '5',
    'level' => 0,
    'id' => '28',
    'name' => '翡翠资讯',
  ),
);
?>